apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  annotations: eks.amazon.com/role-arn: arn:aws:iam::208528724622:role/ssm-for-eks
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  serviceAccountName: cart
  containers:
    - name: cart
      image: 208528724622.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
  initContainers:
    - name: aws-ssm-param-store
      image: 208528724622.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:2.0.0
      args: ["sample:dev-docdb-pass"]

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---


